# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'h-haaks'

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml

configMapGenerator:
  - name: whoami-config
    namespace: 'h-haaks'
    literals:
      - WHOAMI_PORT_NUMBER=8080